### PR TITLE
add $index argument to index to array $formatting

### PR DESCRIPTION
**Pull request by bkulyk**
add $index argument to index to array $formatting.

Used existing (commented) tests, but modified to have index start at 0.

### CODE REVIEW

**Comment by bkulyk** [comment]
Relates to issue #6

**Comment by bkulyk** [comment]
@xcatliu any chance you can review this, please.

**Review by xcatliu — APPROVED** [review]
@bkulyk Sorry for the late reviewing. I am on a long vacation during spring festival. And thanks for your contribution! LGTM

**Comment by xcatliu** [comment]
Published as `0.5.1`

**Pull request merged**
